const jsonData = JSON.stringify({
  allDemos: [
    {
      demoName: "1-9b770a84-52fa-4ae0-ae1c-30e4220a2b95-1-1.dem",
      result: {
        "---David---": {
          Kills: 9,
          EcoKills: 0,
          LightBuyKills: 2,
          TotalValue: 38100,
          Team: 2,
          EcoKillRounds: [],
          LightBuyKillRounds: [20, 20],
        },
        "420ButtWizrd": {
          Kills: 9,
          EcoKills: 1,
          LightBuyKills: 0,
          TotalValue: 34900,
          Team: 1,
          EcoKillRounds: [3],
          LightBuyKillRounds: [],
        },
        BUR: {
          Kills: 14,
          EcoKills: 1,
          LightBuyKills: 3,
          TotalValue: 53850,
          Team: 1,
          EcoKillRounds: [5],
          LightBuyKillRounds: [5, 7, 10],
        },
        BubbaWade55: {
          Kills: 22,
          EcoKills: 5,
          LightBuyKills: 2,
          TotalValue: 69200,
          Team: 2,
          EcoKillRounds: [11, 11, 12, 18, 18],
          LightBuyKillRounds: [12, 20],
        },
        Marshman0: {
          Kills: 11,
          EcoKills: 0,
          LightBuyKills: 2,
          TotalValue: 46200,
          Team: 1,
          EcoKillRounds: [],
          LightBuyKillRounds: [5, 5],
        },
        Sandle: {
          Kills: 13,
          EcoKills: 0,
          LightBuyKills: 1,
          TotalValue: 46900,
          Team: 2,
          EcoKillRounds: [],
          LightBuyKillRounds: [18],
        },
        SerMonk: {
          Kills: 12,
          EcoKills: 0,
          LightBuyKills: 1,
          TotalValue: 42700,
          Team: 1,
          EcoKillRounds: [],
          LightBuyKillRounds: [7],
        },
        Zer00o: {
          Kills: 21,
          EcoKills: 8,
          LightBuyKills: 2,
          TotalValue: 57350,
          Team: 2,
          EcoKillRounds: [11, 12, 15, 15, 15, 15, 18, 18],
          LightBuyKillRounds: [11, 21],
        },
        almosthitme: {
          Kills: 16,
          EcoKills: 3,
          LightBuyKills: 2,
          TotalValue: 52550,
          Team: 1,
          EcoKillRounds: [3, 3, 5],
          LightBuyKillRounds: [7, 10],
        },
        kunmeh13: {
          Kills: 16,
          EcoKills: 2,
          LightBuyKills: 3,
          TotalValue: 59400,
          Team: 2,
          EcoKillRounds: [15, 20],
          LightBuyKillRounds: [12, 12, 17],
        },
      },
    },
  ],
});

console.log("Size of JSON data in bytes:", new Blob([jsonData]).size);
